FROM alpine:3.16@sha256:65a2763f593ae85fab3b5406dc9e80f744ec5b449f269b699b5efd37a07ad32e

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-s3-sync"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-s3-sync"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-s3-sync"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-s3-sync"

RUN apk --update add --no-cache libc6-compat && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

ADD dist/drone-s3-sync /bin/

ENTRYPOINT ["/bin/drone-s3-sync"]
